FROM nginx:alpine

RUN apk add --no-cache openssl && mkdir -p /etc/nginx/certs

# Generate a self-signed certificate at build time
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/certs/server.key \
    -out    /etc/nginx/certs/server.crt \
    -subj "/C=FR/ST=Paris/L=Paris/O=42/CN=localhost"

COPY nginx.conf /etc/nginx/nginx.conf
